# Generated by Django 3.0 on 2020-12-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(choices=[('NO_ANS', 'no-answers'), ('UN_ANS', 'un_answered'), ('DEFAULT', 'default'), ('FEATURED', 'featured'), ('RELATED', 'related'), ('LINKED', 'linked')], default='DEFAULT', max_length=50)),
                ('ids', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
